### PR TITLE
fix uganda national id number

### PR DESCRIPTION
**Pull request by x0apr**
Edited the expression for Uganda National ID Number. It's 14 characters, only Upper case letters and digits

### CODE REVIEW

**Comment by shirsh94** [comment]
Please commit only the changes which are highlighted in the PR functionality message.

**Comment by x0apr** [comment]
> Please commit only the changes which are highlighted in the PR functionality message.

Done

**Comment by x0apr** [comment]
Done

**Comment by shirsh94** [comment]
Please review before you commit. You committed over 30+ changes to the codebase again.

**Comment by x0apr** [comment]
Those other changes are due to the file being opened in an environment with different line length settings, which led to reformatting of the file. The only effective change is the one mentioned. If possible, please take this up as an issue and fix it from your end. ^^

**Comment by x0apr** [comment]
Those other changes were due to different line length settings. Now removed. ^^

**Pull request merged**
